version: 1
update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    commit_message:
       prefix: "[FF-1429]"
    default_reviewers:
       - "credfeto"
    default_assignees:
       - "credfeto"
    allowed_updates:
       - match:
          update_type: all
          dependency_type: indirect
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "daily"
    commit_message:
       prefix: "[FF-1429]"
    default_reviewers:
       - "credfeto"
    default_assignees:
       - "credfeto"
    allowed_updates:
       - match:
          update_type: all
          dependency_type: indirect

